base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", RedirectView.as_view(url="/catalog/", permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^books/$", views.BookListView.as_view(), name="books"),
    url(r"^book/(?P<pk>\d+)$", views.BookDetailView, name="book-detail"),
    url(r"^authors/$", views.AuthorListView.as_view(), name="authors"),
    url(r"^author/(?P<pk>\d+)$", views.AuthorDetailView, name="author-detail"),
    url(r"^mybooks/$", views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    url(r"^borrowed/$", views.BorrowedBooksListView.as_view(), name="all-borrowed"),
    url(
        r"^book/(?P<pk>[-\w]+)/renew/$",
        views.renew_book_librarian,
        name="renew-book-librarian",
    ),
    url(r"^author/create/$", views.AuthorCreate.as_view(), name="author_create"),
    url(
        r"^author/(?P<pk>\d+)/update/$",
        views.AuthorUpdate.as_view(),
        name="author_update",
    ),
    url(
        r"^author/(?P<pk>\d+)/delete/$",
        views.AuthorDelete.as_view(),
        name="author_delete",
    ),
    url(r"^book/create/$", views.BookCreate.as_view(), name="book_create"),
    url(r"^book/(?P<pk>\d+)/update/$", views.BookUpdate.as_view(), name="book_update"),
    url(r"^book/(?P<pk>\d+)/delete/$", views.BookDelete.as_view(), name="book_delete"),
]

catalog/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from datetime import date
import uuid


class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa, etc.)",
    )

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(
        max_length=20,
        help_text="Ingrese el nombre del lenguaje (p. ej. Ingles, Español, etc.)",
    )

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "Author", on_delete=models.SET_NULL, null=True, blank=True
    )
    summary = models.TextField(
        max_length=1000, help_text="Ingrese una breve descripción del libro"
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        help_text="13 Caracteres <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>",
    )
    genre = models.ManyToManyField(
        Genre, help_text="Seleccione un genero para este libro"
    )
    language = models.ForeignKey("Language", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        return ", ".join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="ID único para este libro particular en toda la biblioteca",
    )
    book = models.ForeignKey("Book", on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ("m", "Maintenance"),
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Disponibilidad del libro",
    )

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return str(self.id)


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        return "%s, %s" % (self.last_name, self.first_name)

catalog/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

from .models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 3 weeks (default 2)."
    )

    def clean_renewal_date(self):
        data = self.cleaned_data["renewal_date"]

        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))

        if data > datetime.date.today() + datetime.timedelta(weeks=3):
            raise ValidationError(_("Invalid date - renewal more than 3 weeks ahead"))

        return data


class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data["due_back"]

        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))
        if data > datetime.date.today() + datetime.timedelta(weeks=3):
            raise ValidationError(_("Invalid date - renewal more than 3 weeks ahead"))
        return data

    class Meta:
        model = BookInstance
        fields = [
            "due_back",
        ]
        labels = {
            "due_back": _("Renewal date"),
        }
        help_texts = {
            "due_back": _("Enter a date between now and 3 weeks (default 2)."),
        }

catalog/views.py
import datetime
from django.shortcuts import render
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Book, Author, BookInstance, Genre
from .forms import RenewBookModelForm


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact="a").count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()
    books_madagascar = Book.objects.filter(title__iexact="madagascar")

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_genres": num_genres,
        "num_visits": num_visits,
    }

    return render(
        request,
        "index.html",
        context=context,
    )


class AuthorListView(ListView):
    model = Author
    paginate_by = 10
    template_name = "authors/author_list.html"


def AuthorDetailView(request, pk):
    author_id = get_object_or_404(Author, pk=pk)

    return render(
        request,
        "authors/author_detail.html",
        context={
            "author": author_id,
        },
    )


class BookListView(ListView):
    model = Book
    paginate_by = 3
    context_object_name = "book_list"
    template_name = "books/book_list.html"

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context["some_data"] = "This is just some data"
        return context


def BookDetailView(request, pk):
    book_id = get_object_or_404(Book, pk=pk)

    return render(
        request,
        "books/book_detail.html",
        context={
            "book": book_id,
        },
    )


class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = "books/bookinstance_list_borrowed_user.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact="o")
            .order_by("due_back")
        )


class BorrowedBooksListView(PermissionRequiredMixin, ListView):
    model = BookInstance
    template_name = "books/bookinstance_list_borrowed_user.html"
    paginate_by = 10
    permission_required = "catalog.can_mark_returned"

    def get_queryset(self):
        return BookInstance.objects.order_by("id")


@permission_required("catalog.can_mark_returned")
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == "POST":
        form = RenewBookModelForm(request.POST)

        if form.is_valid():
            book_inst.due_back = form.cleaned_data["due_back"]
            book_inst.save()
            return HttpResponseRedirect(reverse("all-borrowed"))

    else:
        proposed_due_back = datetime.date.today() + datetime.timedelta(weeks=2)
        form = RenewBookModelForm(
            initial={
                "due_back": proposed_due_back,
            }
        )

    return render(
        request,
        "books/book_renew_librarian.html",
        {"form": form, "bookinst": book_inst},
    )


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    template_name = "authors/author_form.html"
    permission_required = "catalog.add_author"
    fields = "__all__"
    initial = {
        "date_of_birth": "05/01/2018",
    }


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    template_name = "authors/author_form.html"
    permission_required = "catalog.change_author"
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    template_name = "authors/author_confirm_delete.html"
    permission_required = "catalog.delete_author"
    success_url = reverse_lazy("authors")


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    template_name = "books/book_form.html"
    permission_required = "catalog.add_book"
    fields = "__all__"
    initial = {
        "status": "a",
    }


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    template_name = "books/book_form.html"
    permission_required = "catalog.change_book"
    fields = "__all__"


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    template_name = "books/book_confirm_delete.html"
    permission_required = "catalog.delete_book"
    success_url = reverse_lazy("books")

catalog/templates/books/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-primary" type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/books/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/books/book_form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class="btn btn-primary" type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/books/book_list.html
{% extends "base.html" %}

{% block title %}
  <title>Book List</title>
{% endblock title %}

{% block content %}
    <h1>Book List</h1>
    <p>{{ some_data }}</p>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/books/book_renew_librarian.html
{% extends "base.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/books/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
        ({{ bookinst.due_back }})

        {% if perms.catalog.can_mark_returned and bookinst.borrower.username %}
          - Borrower: {{ bookinst.borrower.username }}
          {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
        {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}